services:
  - type: web
    name: automated-timetable-iiit-dharwad
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn upload_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
